.TH leafpad-fltk 1 "January 2024" "leafpad-fltk 0.24" "User Commands"
.SH NAME
leafpad-fltk - a simple FLTK-based text editor
.SH SYNOPSIS
.B leafpad-fltk
[
.I OPTIONS
] [
.I FILE
]
.SH DESCRIPTION
leafpad-fltk is a simple, lightweight text editor for the X Window System that uses the FLTK toolkit. It is designed to be fast and easy to use.
.SH OPTIONS
This program follows the usual GNU command line syntax, with long options starting with two dashes (`--`). A summary of options is included below.
.TP
.B --version
Show version of program.
.TP
.B --help
Show summary of options.
.SH SEE ALSO
.BR fltk (1)
.SH AUTHOR
This manual page was written by Jason Wysotski.
